version: '3'
services:
  base:
    image: node:17
    volumes:
      - nodemodules:/usr/src/service/node_modules
      - .:/usr/src/service/
    working_dir: /usr/src/service/
  install:
    extends:
      service: base
    command: npm i
volumes:
  nodemodules:
    external: true